		 
	</div>
</div>

	<style>	
		.nav-glyphish-example .ui-btn .ui-btn-inner { padding-top: 40px !important; }
		.nav-glyphish-example .ui-btn .ui-icon { width: 30px!important; height: 30px!important; margin-left: -15px !important; box-shadow: none!important; -moz-box-shadow: none!important; -webkit-box-shadow: none!important; -webkit-border-radius: 0 !important; border-radius: 0 !important; }
		#viewComments .ui-icon { background:  url(img/glyphish/icons/09-chat-2.png) no-repeat; background-size: 24px 22px; }
		#viewProjects .ui-icon { background:  url(img/glyphish/icons/176-ipad.png) no-repeat; background-size: 22px 28px; }
		#viewUsers .ui-icon { background:  url(img/glyphish/icons/112-group.png) no-repeat; background-size: 32px 21px; }
		#addComment .ui-icon { background:  url(img/glyphish/icons/08-chat.png) no-repeat; background-size: 24px 22px; }
		#addProject .ui-icon { background:  url(img/glyphish/icons/32-iphone.png) no-repeat; background-size: 16px 28px; }
		#addUser .ui-icon { background:  url(img/glyphish/icons/111-user.png) no-repeat; background-size: 24px 22px; }
	</style>
	
	<div data-role="footer" class="nav-glyphish-example">
		<div data-role="navbar" class="nav-glyphish-example" data-grid="b">
		<ul>
			<li><a href="viewComments.php" id="viewComments" data-icon="custom">View Comments</a></li>
			<li><a href="viewProjects.php" id="viewProjects" data-icon="custom">View Projects</a></li>
			<li><a href="viewUsers.php" id="viewUsers" data-icon="custom">View Users</a></li>
		</ul>
		</div>
	</div>
	<div data-role="footer" class="nav-glyphish-example">
		<div data-role="navbar" class="nav-glyphish-example" data-grid="b">
		<ul>
			<li><a href="createComment.php" id="addComment" data-icon="custom">Add Comment</a></li>
			<li><a href="createProject.php" id="addProject" data-icon="custom">Add Project</a></li>
			<li><a href="createUser.php" id="addUser" data-icon="custom">Add User</a></li>
		</ul>
		</div>
		<h1><a href="http://edustudios.com/projects/feedback-the-captivate-review-tools/" target="_blank">feedback</a> by: <a href="http://edustudios.com" target="_blank">eduStudios</a></h1> 
	</div>
</body>
</html>