<h3>MENU</h3>
<table border="3" bordercolor="#FFCC00" style="background-color:#FFFFCC" width="460px" cellpadding="10" cellspacing="10">
	<tr>
		<td>
			<p>
				<a href='createUser.php'>createUser</a>
				<a href='viewUsers.php'>viewUsers</a>
				<a href='updateUser.php'>updateUser</a>
			</p>
		</td>
		<td>
			<p>
				<a href='createComment.php'>createComment</a>
				<a href='viewComments.php'>viewComments</a>
				<a href='updateComment.php'>updateComment</a>
			</p>
		</td>
		<td>
			<p>
				<a href='createProject.php'>createProject</a>
				<a href='viewProjects.php'>viewProjects</a>
				<a href='updateProject.php'>updateProject</a>
			</p>
		</td>
	</tr>
</table>

<br/>
<hr/>
<br/>