<div data-role="page" class="type-home">
	<div data-role="header"> 
		<h1>MENU</h1> 
	</div> 
	
	<div data-role="content">
    	<div class="content-secondary">
		
		USERS: 
		<div data-role="controlgroup" data-type="horizontal">
			<a href="createUser.php" data-role="button" data-icon="plus">Create</a>
			<a href="viewUsers.php" data-role="button" data-icon="grid">View</a>
		</div>
		COMMENTS: 
		<div data-role="controlgroup" data-type="horizontal">
			<a href="createComment.php" data-role="button" data-icon="plus">Create</a>
			<a href="viewComments.php" data-role="button" data-icon="grid">View</a>
		</div>
		PROJECTS: 
		<div data-role="controlgroup" data-type="horizontal">
			<a href="createProject.php" data-role="button" data-icon="plus">Create</a>
			<a href="viewProjects.php" data-role="button" data-icon="grid">View</a>
		</div>
	
		<br/>
		<hr/>
		<br/>